Я добавил popover))
AbdurahimNasirov/JSONPlaceholder pull request #7
Opened 2022-01-30 17:59 UTC by AbdurahimNasirov

2022-01-31 06:01 UTC, twixy123 commented on src/components/auth/AddPost.vue
> +                :counter="`∞`"
зачем использовать динамический аттрибут и передавать туда строку?
:counter="`∞`" => counter="∞"

2022-01-31 06:03 UTC, twixy123 commented on src/components/auth/AddPost.vue
> +                @input="$v.name.$touch()"
Во vuelidate есть настройка что бы автоматически проверял... Такое решение не правильно
https://vuelidate.js.org/#sub-basic-form
Почитай внимательно

2022-01-31 06:04 UTC, AbdurahimNasirov commented on src/components/auth/AddPost.vue
> +                :counter="`∞`"
остальные правильно ?

2022-01-31 06:04 UTC, twixy123 commented on src/components/auth/AddPost.vue
> +              <v-select
Что за табуляция? Не правильный отступ!

2022-01-31 06:06 UTC, twixy123 commented on src/components/auth/AddPost.vue
>  <style lang="scss">
Почему не используешь scoped? Используй scoped

2022-01-31 06:08 UTC, twixy123 commented on src/components/auth/AddPost.vue
> +                @input="$v.name.$touch()"
почему v-model="title"
а проверяешь name $v.name.touch()?
Внимательней!

2022-01-31 06:09 UTC, twixy123 commented on src/components/auth/AddPost.vue
> +          this.clear();
Что за метод clear? Непонятно что чистит. Напиши не clear, а clearAllData

2022-01-31 06:11 UTC, twixy123 commented on src/components/auth/AddPost.vue
> +.absolute-add-btn-post {
Некорректный нэйминг, какой еще .absolute-add-btn-post?
.absolute-add-btn-post => .add-btn-post
Если absolute это дополнение пиши .add-btn-post--absolute
посмотри bem https://www.youtube.com/watch?v=HihYQVuH64U

2022-01-31 06:12 UTC, twixy123 commented on src/components/auth/AddUser.vue
> +    </v-app>
повторяется код, вынеси этот popover в отдельный компонент

2022-01-31 06:12 UTC, twixy123 commented on src/components/auth/AddUser.vue
> +    <!-- <form>
Убери все комментарии если больше не нужны

2022-01-31 06:14 UTC, twixy123 commented on src/components/auth/AddUser.vue
> +          console.log(error);
Ты никак не показываешь на интерфейсе что ты не смог добавить нового пользователя.
Нужно выводить какое нибудь сообщение что не получилось добавить пользвателя. Никто кроме тебя смотреть в log не будет

2022-01-31 06:16 UTC, twixy123 commented on src/components/auth/AddUser.vue
> +    },
Почему метод называется showModalWindow если ты там меняешь на противоположное значение
showModalWindow -> triggerModalWindow
showModalWindow ->switchModalWindow

2022-01-31 06:19 UTC, twixy123 commented on src/components/posts/PostsItem.vue
> +      <router-link :to="`${this.$route.params.userId}/post/${post.id}`">{{post.title}}</router-link>
Переноси на строки, не понятно что ты тут пишешь, не читается!
${$route.params.userId}/post/${post.id} ->
{
  name: "routeName",
  params: {
    userId: $route.params.userId,
    postId: post.id,
  }
}

Почитай внимательно https://router.vuejs.org/guide/essentials/named-routes.html

2022-01-31 06:20 UTC, twixy123 commented on src/router/index.js
> +      component: () => import('../views/Post.vue')
Не используй точечные пути
Используй относительные
../views/Post.vue -> @/views/Post.vue

2022-01-31 06:21 UTC, twixy123 requested changes
Поправь все комментарии не только в этих компонентах но и во всех во всем проектк

2022-02-01 16:14 UTC, twixy123 commented on src/components/auth/AddPost.vue
>  <style lang="scss">
Почему не исправил scoped?

2022-02-01 16:18 UTC, twixy123 commented on src/components/posts/PostsItem.vue
> +      :to="{name: 'Post', params: { userId: $route.params.userId, postId: post.id }, component: () =>import('@/views/Post.vue')}"
делай переносы на строки. В одну строку очень не читабельно

2022-02-01 16:20 UTC, twixy123 commented on src/components/auth/AddUser.vue
> +    </v-app>
А где теперь popover?

2022-02-02 06:43 UTC, twixy123 approved these changes

2022-02-02 06:58 UTC, merged